# Generated by Django 4.1 on 2022-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_delete_test_remove_category_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default="{% static %}/images/placeholder.png",
                upload_to="media/recipes/",
            ),
        ),
    ]
