# Generated by Django 4.1 on 2022-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="editor_pick",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default="static/placeholder.png", upload_to="recipes/"
            ),
        ),
    ]
