# Generated by Django 4.1 on 2022-08-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0007_alter_recipe_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="cat_ingredients", to="food.ingredient"
            ),
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="category",
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ManyToManyField(related_name="category", to="food.category"),
        ),
    ]
