# Generated by Django 4.1 on 2022-08-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0009_alter_recipe_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(
                default="static/default-ingredient.svg", upload_to="ingredients/"
            ),
        ),
    ]
