# Generated by Django 4.1 on 2022-08-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0010_ingredient_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(
                default="static/placeholder-ing.png", upload_to="ingredients/"
            ),
        ),
    ]
