# Generated by Django 4.1 on 2022-08-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0011_alter_ingredient_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(
                default="static/placeholdering.png", upload_to="ingredients/"
            ),
        ),
    ]
